### PR TITLE
Add daq-rabbitmq service

### PR DESCRIPTION
**Pull request by joeshannon**

### CODE REVIEW

**Comment by joeshannon** [comment]
Most of the diff can currently be ignored. My branch is based on Giles's update branch which hasn't been merged yet.

**Comment by joeshannon** [comment]
Question for @gilesknap 

`ec ps` doesn't list this as running:
```
$ ec ps
| name              | version       | running | restarts | deployed            |
|-------------------|---------------|---------|----------|---------------------|
| epics-opis        | 2024.3.8430-b | true    | 0        | 2024-03-15 09:24:06 |
| bl45p-mo-brick-01 | 2024.3.9709-b | true    | 0        | 2024-03-15 10:44:30 |
(ec) $ ec ps --all
| name              | version       | running | restarts | deployed            |
|-------------------|---------------|---------|----------|---------------------|
| epics-opis        | 2024.3.8430-b | true    | 0        | 2024-03-15 09:24:06 |
| gda-server-p45    | master        | false   | 0        | 2022-06-06 15:49:06 |
| bl45p-ea-dcam-01  | 2024.3.9f10-b | false   | 0        | 2024-03-15 11:18:45 |
| bl45p-ea-dcam-02  | 2024.3.a00b-b | false   | 0        | 2024-03-15 11:22:55 |
| bl45p-mo-brick-01 | 2024.3.9709-b | true    | 0        | 2024-03-15 10:44:30 |
| bl45p-mo-panda-01 | 2024.3.97a0-b | false   | 0        | 2024-03-15 10:47:01 |
| daq-rabbitmq      | 2024.3.df3a-b | false   | 0        | 2024-03-27 15:52:53 |
```
Is this because it was deployed with `deploy-local`?

**Comment by gilesknap** [comment]
Hi @joeshannon no it should be shown as running. It looks like it has deployed into the cluster OK.

@marcelldls please could you take a look as why this has running=false.  thanks.

**Comment by gilesknap** [comment]
@joeshannon I merged 'update' and rebased this so the PR looks more legible.

**Comment by marcelldls** [comment]
Apologies it took a while to get permissions for the cluster. I found a difference in the labels. We expect "app" but find "app.kubernetes.io/instance" (which is an accepted label https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/)

```
            "apiVersion": "v1",
            "kind": "Pod",
            "metadata": {
                "annotations": {
                    "kubernetes.io/limit-ranger": "LimitRanger plugin set: ephemeral-storage request for container bl45p-mo-brick-01; ephemeral-storage limit for container bl45p-mo-brick-01"
                },
                "creationTimestamp": "2024-03-15T10:45:28Z",
                "generateName": "bl45p-mo-brick-01-",
                "labels": {
                    "app": "bl45p-mo-brick-01",
                    "controller-revision-hash": "bl45p-mo-brick-01-598dc8d96f",
                    "ioc_group": "bl45p",
                    "is_ioc": "true",
                    "location": "bl45p",
                    "statefulset.kubernetes.io/pod-name": "bl45p-mo-brick-01-0"
                },
```

```
            "apiVersion": "v1",
            "kind": "Pod",
            "metadata": {
                "annotations": {
                    "checksum/config": "e37a96caecd8c72379f34c458099285bcf9d5030775dc3c479e8217e959c7df3",
                    "checksum/secret": "c821749412555644ad9787e184c6ccf810bb1611a44b2c46c4a5ebffcc236851",
                    "kubernetes.io/limit-ranger": "LimitRanger plugin set: cpu, ephemeral-storage, memory request for container rabbitmq; cpu, ephemeral-storage, memory limit for container rabbitmq",
                    "prometheus.io/path": "/metrics",
                    "prometheus.io/port": "8080",
                    "prometheus.io/scrape": "true"
                },
                "creationTimestamp": "2024-03-27T20:37:19Z",
                "generateName": "daq-rabbitmq-",
                "labels": {
                    "app.kubernetes.io/instance": "daq-rabbitmq",
                    "app.kubernetes.io/managed-by": "Helm",
                    "app.kubernetes.io/name": "rabbitmq",
                    "controller-revision-hash": "daq-rabbitmq-bbb8647fb",
                    "helm.sh/chart": "rabbitmq-11.16.2",
                    "statefulset.kubernetes.io/pod-name": "daq-rabbitmq-0"
                },
```
Will work on the fix discussed

**Pull request merged**
